/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/dTdHyNVTLSp
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Dialog, DialogTrigger, DialogContent, DialogHeader } from "@/app/components/ui/dialog"
import { Button } from "@/app/components/ui/button"
import { Avatar, AvatarImage, AvatarFallback } from "@/app/components/ui/avatar"
import { Textarea } from "@/app/components/ui/textarea"
import { useState } from "react"

export function Chatbot() {
  const [isOpen, setIsOpen] = useState(false)

  return (
    <Dialog open={isOpen} onOpenChange={setIsOpen}>
      <DialogTrigger asChild>
        <Button variant="ghost" className="rounded-full bg-primary text-primary-foreground">
          <MessageCircleIcon className="w-6 h-6" />
        </Button>
      </DialogTrigger>
      <DialogContent className="sm:max-w-[400px] w-full">
        <div className="flex flex-col h-[500px]">
          <DialogHeader className="flex items-center gap-4 border-b px-4 py-3">
            <Avatar className="h-8 w-8">
              <AvatarImage src="/placeholder-user.jpg" alt="ChatGPT" />
              <AvatarFallback>CG</AvatarFallback>
            </Avatar>
            <div className="text-sm font-medium">Larry</div>
          </DialogHeader>
          <div className="flex-1 overflow-auto p-4">
            <div className="grid gap-4">
              <div className="flex items-start gap-4">
                <Avatar className="h-8 w-8">
                  <AvatarImage src="/placeholder-user.jpg" alt="You" />
                  <AvatarFallback>YO</AvatarFallback>
                </Avatar>
                <div className="bg-muted rounded-lg p-3 max-w-[80%]">
                  <p className="text-sm">
                    Hi there! I&apos;m looking for some help with a project I&apos;m working on. Do you have a few
                    minutes to chat?
                  </p>
                </div>
              </div>
              <div className="flex items-start gap-4 justify-end">
                <div className="bg-primary rounded-lg p-3 max-w-[80%] text-primary-foreground">
                  <p className="text-sm">Sure, I&apos;d be happy to help! What kind of project are you working on?</p>
                </div>
                <Avatar className="h-8 w-8">
                  <AvatarImage src="/placeholder-user.jpg" alt="ChatGPT" />
                  <AvatarFallback>CG</AvatarFallback>
                </Avatar>
              </div>
              <div className="flex items-start gap-4">
                <Avatar className="h-8 w-8">
                  <AvatarImage src="/placeholder-user.jpg" alt="You" />
                  <AvatarFallback>YO</AvatarFallback>
                </Avatar>
                <div className="bg-muted rounded-lg p-3 max-w-[80%]">
                  <p className="text-sm">
                    I&apos;m building a new website for my small business. I need help with the design and
                    functionality.
                  </p>
                </div>
              </div>
              <div className="flex items-start gap-4 justify-end">
                <div className="bg-primary rounded-lg p-3 max-w-[80%] text-primary-foreground">
                  <p className="text-sm">
                    Okay, great! Let&apos;s start by discussing your goals for the website. What kind of features or
                    functionality are you looking for?
                  </p>
                </div>
                <Avatar className="h-8 w-8">
                  <AvatarImage src="/placeholder-user.jpg" alt="ChatGPT" />
                  <AvatarFallback>CG</AvatarFallback>
                </Avatar>
              </div>
            </div>
          </div>
          <div className="border-t px-4 py-3">
            <div className="flex items-center gap-2">
              <Textarea
                placeholder="Type your message..."
                className="flex-1 resize-none rounded-lg border border-input bg-transparent px-3 py-2 text-sm placeholder:text-muted-foreground focus:outline-none focus:ring-1 focus:ring-ring disabled:cursor-not-allowed disabled:opacity-50"
              />
              <Button type="submit" variant="ghost" className="rounded-full">
                <SendIcon className="w-5 h-5" />
              </Button>
            </div>
          </div>
        </div>
      </DialogContent>
    </Dialog>
  )
}

function MessageCircleIcon(props: React.SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M7.9 20A9 9 0 1 0 4 16.1L2 22Z" />
    </svg>
  )
}

function SendIcon(props: React.SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="m22 2-7 20-4-9-9-4Z" />
      <path d="M22 2 11 13" />
    </svg>
  )
}
